import JSZip from 'jszip'

/**
 * Widget ZIP Builder
 * Packages generated widget code into a downloadable ZIP file
 * compatible with ArcGIS Experience Builder widget structure
 */

export interface WidgetPackage {
  widgetName: string
  code: string
  config?: {
    name?: string
    description?: string
    version?: string
    [key: string]: unknown
  }
}

/**
 * Builds a complete widget ZIP package for ExB
 */
export async function buildWidgetZip(packageData: WidgetPackage): Promise<Blob> {
  const zip = new JSZip()

  const widgetName = packageData.widgetName || 'widget'
  const widgetFolder = zip.folder(widgetName)

  if (!widgetFolder) {
    throw new Error('Failed to create widget folder in ZIP')
  }

  // Create widget structure
  const srcFolder = widgetFolder.folder('src')
  if (!srcFolder) {
    throw new Error('Failed to create src folder in ZIP')
  }

  const runtimeFolder = srcFolder.folder('runtime')
  if (!runtimeFolder) {
    throw new Error('Failed to create runtime folder in ZIP')
  }

  // Add main widget code
  runtimeFolder.file('widget.tsx', packageData.code)

  // Add config.json
  const config = {
    name: packageData.config?.name || widgetName,
    label: packageData.config?.name || widgetName,
    description: packageData.config?.description || 'Generated by VibeGIS',
    version: packageData.config?.version || '1.0.0',
    ...packageData.config,
  }

  widgetFolder.file('config.json', JSON.stringify(config, null, 2))

  // Add manifest.json (ExB widget manifest)
  const manifest = {
    name: config.name,
    label: config.label,
    description: config.description,
    version: config.version,
    author: 'VibeGIS',
    copyright: '',
    license: '',
    properties: {},
    supportedLocales: ['en'],
    defaultSize: {
      width: 400,
      height: 400,
    },
  }

  widgetFolder.file('manifest.json', JSON.stringify(manifest, null, 2))

  // Add package.json for widget
  const packageJson = {
    name: `@vibegis/${widgetName}`,
    version: config.version,
    description: config.description,
    main: 'src/runtime/widget.tsx',
    dependencies: {
      'jimu-core': '^1.19.0',
      'jimu-arcgis': '^1.19.0',
      react: '^19.0.0',
      'react-dom': '^19.0.0',
    },
  }

  widgetFolder.file('package.json', JSON.stringify(packageJson, null, 2))

  // Add README
  const readme = `# ${config.name}

${config.description}

## Generated by VibeGIS

This widget was generated using the BMAD methodology:
- **Business**: Analyzed requirements
- **Manage**: PRD created
- **Architect**: Technical structure defined
- **Develop**: Code generated

## Installation

1. Extract this ZIP file
2. Copy the widget folder to your Experience Builder widget directory
3. Follow ExB widget installation procedures

## Usage

[Add usage instructions here]

---

Generated on ${new Date().toISOString()}
`

  widgetFolder.file('README.md', readme)

  // Generate ZIP blob
  return await zip.generateAsync({ type: 'blob' })
}

/**
 * Validates widget code structure
 */
export function validateWidgetCode(code: string): { valid: boolean; errors: string[] } {
  const errors: string[] = []

  // Basic validation checks
  if (!code.includes('jimu-core') && !code.includes('jimu-arcgis')) {
    errors.push('Missing Jimu framework imports')
  }

  if (!code.includes('React') && !code.includes('react')) {
    errors.push('Missing React import')
  }

  if (!code.includes('export') && !code.includes('export default')) {
    errors.push('Missing export statement')
  }

  return {
    valid: errors.length === 0,
    errors,
  }
}
