import { useState } from 'react'
import { Code2 } from 'lucide-react'
import type { GeneratorStepProps } from '../types'

/**
 * Step 03: ARCHITECT
 * Architect Agent UI - Displays technical architecture and Jimu structure
 */
export default function ArchitectStep({ onNext, onBack, data, updateData }: GeneratorStepProps) {
  const [architecture, setArchitecture] = useState(data?.architecture || '')
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGenerateArchitecture = async () => {
    setIsGenerating(true)
    // TODO: Call Architect Agent API with PRD from previous step
    // const generatedArch = await generateArchitecture(data.prd)
    
    // Simulate architecture generation
    setTimeout(() => {
      const mockArch = `# Technical Architecture

## Jimu Framework Structure
\`\`\`
widget/
├── src/
│   ├── runtime/
│   │   └── widget.tsx
│   ├── setting/
│   │   └── setting.tsx
│   └── config.json
\`\`\`

## Component Architecture
- Main widget component
- Map integration
- State management

## ArcGIS API Usage
- MapView integration
- Feature layer access
- Event handling`
      
      setArchitecture(mockArch)
      updateData({ architecture: mockArch })
      setIsGenerating(false)
    }, 2000)
  }

  const handleNext = () => {
    if (!architecture.trim()) {
      handleGenerateArchitecture()
      return
    }
    updateData({ architecture })
    onNext?.()
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 bg-gradient-to-br from-cyan-500/20 to-purple-600/20 rounded-lg flex items-center justify-center text-cyan-400">
          <Code2 className="w-6 h-6" />
        </div>
        <div>
          <div className="text-sm font-mono text-cyan-400 mb-1">STEP 03</div>
          <h2 className="text-2xl font-black">ARCHITECT</h2>
          <p className="text-gray-400 text-sm">Architect Agent defines Jimu structure and technical approach.</p>
        </div>
      </div>

      <div className="bg-geodark-secondary border border-cyan-500/20 rounded-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <label className="block text-sm font-bold text-gray-300">
            Technical Architecture
          </label>
          {!architecture && (
            <button
              onClick={handleGenerateArchitecture}
              disabled={isGenerating}
              className="px-4 py-2 bg-cyan-500/20 border border-cyan-500/50 text-cyan-400 rounded-lg hover:bg-cyan-500/30 transition-colors text-xs font-bold disabled:opacity-50"
            >
              {isGenerating ? 'Generating...' : 'Generate Architecture'}
            </button>
          )}
        </div>
        <textarea
          value={architecture}
          onChange={(e) => setArchitecture(e.target.value)}
          placeholder="Architecture will be generated by Architect Agent..."
          className="w-full h-96 bg-geodark-tertiary border border-gray-800 rounded-lg p-4 text-gray-100 font-mono text-sm focus:outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/20 resize-none"
        />
        <p className="text-xs text-gray-500 mt-2 font-mono">
          Review the technical approach. This defines how the widget will be structured.
        </p>
      </div>

      <div className="flex items-center justify-between pt-4 border-t border-gray-800">
        <button
          onClick={onBack}
          className="px-6 py-3 border border-gray-800 text-gray-400 rounded-lg hover:border-gray-700 hover:text-gray-300 transition-colors font-bold"
        >
          Back
        </button>
        <button
          onClick={handleNext}
          disabled={!architecture.trim() || isGenerating}
          className="px-8 py-3 bg-gradient-to-r from-cyan-500 to-purple-600 text-white rounded-lg hover:shadow-neon-cyan-lg transition-all font-bold disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
        >
          Generate Code
          <span className="text-xs">→</span>
        </button>
      </div>
    </div>
  )
}
