import { useState } from 'react'
import { FileText } from 'lucide-react'
import type { GeneratorStepProps } from '../types'

/**
 * Step 02: SPECIFY
 * PM Agent UI - Displays and allows editing of generated PRD
 */
export default function SpecifyStep({ onNext, onBack, data, updateData }: GeneratorStepProps) {
  const [prd, setPrd] = useState(data?.prd || '')
  const [isGenerating, setIsGenerating] = useState(false)

  const handleGeneratePRD = async () => {
    setIsGenerating(true)
    // TODO: Call PM Agent API with analysis from previous step
    // const generatedPRD = await generatePRD(data.widgetIdea, data.analysis)
    
    // Simulate PRD generation
    setTimeout(() => {
      const mockPRD = `# Widget PRD: ${data?.widgetIdea || 'Widget'}

## Functional Requirements
- [ ] Requirement 1
- [ ] Requirement 2

## UI Specifications
- Component structure
- Styling approach

## Technical Considerations
- ArcGIS API usage
- Jimu framework integration`
      
      setPrd(mockPRD)
      updateData({ prd: mockPRD })
      setIsGenerating(false)
    }, 2000)
  }

  const handleNext = () => {
    if (!prd.trim()) {
      handleGeneratePRD()
      return
    }
    updateData({ prd })
    onNext?.()
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="w-12 h-12 bg-gradient-to-br from-cyan-500/20 to-purple-600/20 rounded-lg flex items-center justify-center text-cyan-400">
          <FileText className="w-6 h-6" />
        </div>
        <div>
          <div className="text-sm font-mono text-cyan-400 mb-1">STEP 02</div>
          <h2 className="text-2xl font-black">SPECIFY</h2>
          <p className="text-gray-400 text-sm">PM Agent generates PRD with functional requirements and UI specs.</p>
        </div>
      </div>

      <div className="bg-geodark-secondary border border-cyan-500/20 rounded-lg p-6">
        <div className="flex items-center justify-between mb-4">
          <label className="block text-sm font-bold text-gray-300">
            Product Requirements Document
          </label>
          {!prd && (
            <button
              onClick={handleGeneratePRD}
              disabled={isGenerating}
              className="px-4 py-2 bg-cyan-500/20 border border-cyan-500/50 text-cyan-400 rounded-lg hover:bg-cyan-500/30 transition-colors text-xs font-bold disabled:opacity-50"
            >
              {isGenerating ? 'Generating...' : 'Generate PRD'}
            </button>
          )}
        </div>
        <textarea
          value={prd}
          onChange={(e) => setPrd(e.target.value)}
          placeholder="PRD will be generated by PM Agent..."
          className="w-full h-96 bg-geodark-tertiary border border-gray-800 rounded-lg p-4 text-gray-100 font-mono text-sm focus:outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/20 resize-none"
        />
        <p className="text-xs text-gray-500 mt-2 font-mono">
          Review and edit the PRD. This will guide the architecture phase.
        </p>
      </div>

      <div className="flex items-center justify-between pt-4 border-t border-gray-800">
        <button
          onClick={onBack}
          className="px-6 py-3 border border-gray-800 text-gray-400 rounded-lg hover:border-gray-700 hover:text-gray-300 transition-colors font-bold"
        >
          Back
        </button>
        <button
          onClick={handleNext}
          disabled={!prd.trim() || isGenerating}
          className="px-8 py-3 bg-gradient-to-r from-cyan-500 to-purple-600 text-white rounded-lg hover:shadow-neon-cyan-lg transition-all font-bold disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
        >
          Continue to Architecture
          <span className="text-xs">→</span>
        </button>
      </div>
    </div>
  )
}
