/**
 * Supabase Database Types
 * 
 * This file will be auto-generated by Supabase CLI when you run:
 * npx supabase gen types typescript --project-id <your-project-id> > src/types/database.ts
 * 
 * For now, this is a placeholder. Replace with actual types after connecting to Supabase.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // Tables will be defined here after Supabase setup
      [key: string]: {
        Row: Record<string, unknown>
        Insert: Record<string, unknown>
        Update: Record<string, unknown>
      }
    }
    Views: {
      [key: string]: {
        Row: Record<string, unknown>
      }
    }
    Functions: {
      [key: string]: {
        Args: Record<string, unknown>
        Returns: unknown
      }
    }
    Enums: {
      [key: string]: string
    }
  }
}
